name: 'php-code-sniffer-standard'
services:
    php82:
        type: 'php:8.2'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
    php83:
        type: 'php:8.3'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
    php84:
        type: 'php:8.4'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'
    php85:
        type: 'php:8.5'
        xdebug: true
        overrides:
            environment:
                PHP_IDE_CONFIG: 'serverName=appserver'
                XDEBUG_TRIGGER: '1'

tooling:
    phpcs:
        cmd:
            -   php82: 'vendor/bin/phpcs'
            -   php83: 'vendor/bin/phpcs'
            -   php84: 'vendor/bin/phpcs'
            -   php85: 'vendor/bin/phpcs'
    phpstan:
        cmd:
            -   php82: 'vendor/bin/phpstan'
            -   php83: 'vendor/bin/phpstan'
            -   php84: 'vendor/bin/phpstan'
            -   php85: 'vendor/bin/phpstan'
    phpunit:
        cmd:
            -   php82: 'vendor/bin/phpunit'
            -   php83: 'vendor/bin/phpunit'
            -   php84: 'vendor/bin/phpunit'
            -   php85: 'vendor/bin/phpunit'
